### ISSUE TITLE
TypeError: expected string or bytes-like object, got 'NoneType'

### ISSUE THREAD

**Issue by rhetticent** [mathisdt/nextcloud-news-filter#2]
# Summary
I (seemingly) randomly started seeing failures when the script is run if a feedId is not specified.

# config.ini setup
(condensed to one filter - this error occurs on all filters, regardless whether an article is found that matches the filter or not)
```
[login]
address = https://xxx.xxx.com
username = xxx
password = xxx

# Optional parameters:
#
# feedId: restrict rule to just this feed.
# ex: feedId = 51
#
# titleRegex: apply rule to article title
# ex: titleRegex = \bCOLOR\b (use \b to trap word boundaries)
#
# bodyRegex: apply rule to article body
# ex: bodyRegex = \bCOLOR\b (use \b to trap word boundaries)
#
# hoursAge: apply rule if "pubDate" is older than this
# ex: hoursAge = 72

[ALL-Sonos]
titleRegex = \bsonos\b
```

# Results
```
2024-02-22 14:04:30,428 - root - DEBUG - starting run
2024-02-22 14:04:30,430 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): xxx.xxx.com:443
2024-02-22 14:04:30,568 - urllib3.connectionpool - DEBUG - xxx.xxx.com:443 "GET /index.php/apps/news/api/v1-3/items HTTP/1.1" 200 77326
Traceback (most recent call last):
  File "/home/xxx/nextcloud-news-filter/main.py", line 72, in <module>
    or one_filter['titleRegex'].search(item['title'])) \
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

**Comment by rhetticent** [comment]
Update: Changing line 68 from None to "NoneType" seems to clear this up. This is my first ever pull request, so if it's not the correct way to propose a fix, just let me know! :)

**Comment by mathisdt** [comment]
Thank you for your detailed description! I think your regular expression is correct, but lacks the necessary escaping. The filtering program is written in Python (as you know), and inside Python Strings a single backslash `\` (which you want as the first character in your regex) has to be written with an escaping character before - which also is a backslash.

Your filter should work when it is defined like this in `config.ini`:

```
[ALL-Sonos]
titleRegex = \\bsonos\\b
```

For reference: at the top of Python's [regular expression module documentation](https://docs.python.org/3/library/re.html), there is a short explanation of the necessary escaping. The script can't use the simplified "raw string" notation because the strings are loaded from the `.ini` file, so the escaping cannot be circumvented. (I have updated the readme to direct anyone struggling with this to the same link.)

Please comment whether this helped you or not.

**Comment by rhetticent** [comment]
Thanks so much for the follow up! I did some more digging last night and found the culprit by testing filters on each feed, one-by-one. It turned out to be a misbehaving [article from a Tumblr blog that came in with no title](https://unwrapping.tumblr.com/post/742999958683320320). Since Tumblr posts can contain just a photo, I'm guessing the function bugged out when it came across this title-less post.

![Screenshot from 2024-02-23 15-04-42](https://github.com/mathisdt/nextcloud-news-filter/assets/98632453/0df4691b-699c-4d8c-962b-b3ba6851a99a)

Once I found the offending feed, as soon as I marked this one article as "read", the error went away.

Just for good measure, I tried it again by marking the offending article as unread and escaping `\b`'s backslashes with an additional `\`, but it failed in the same manner as before. No worries though - it seems to be a pretty obscure edge case, so I'll probably just keep it in mind if I see failures in the future. :)

(Sidebar - thanks so much for building this tool. It's a massive time saver for me!)
